// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:

// import 'firebase_options.dart';
// // ...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDObwrx3c4bUa-Om47oBGI17VKAISECnQ0',
    appId: '1:778337091643:web:878f194e8409bee1a65c1e',
    messagingSenderId: '778337091643',
    projectId: 'mindow-d931f',
    authDomain: 'mindow-d931f.firebaseapp.com',
    storageBucket: 'mindow-d931f.firebasestorage.app',
    measurementId: 'G-G8K28S45B1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt-MacyKAAS3nyhuTduvYF9nbjzCbOB5Y',
    appId: '1:778337091643:android:62612c823e9c1072a65c1e',
    messagingSenderId: '778337091643',
    projectId: 'mindow-d931f',
    storageBucket: 'mindow-d931f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzOe0uKD6NKhgCduw89-PIsBn_eOPwiTI',
    appId: '1:778337091643:ios:449453fa111410caa65c1e',
    messagingSenderId: '778337091643',
    projectId: 'mindow-d931f',
    storageBucket: 'mindow-d931f.firebasestorage.app',
    iosBundleId: 'com.example.mindow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzOe0uKD6NKhgCduw89-PIsBn_eOPwiTI',
    appId: '1:778337091643:ios:449453fa111410caa65c1e',
    messagingSenderId: '778337091643',
    projectId: 'mindow-d931f',
    storageBucket: 'mindow-d931f.firebasestorage.app',
    iosBundleId: 'com.example.mindow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDObwrx3c4bUa-Om47oBGI17VKAISECnQ0',
    appId: '1:778337091643:web:fe3b4909a681e245a65c1e',
    messagingSenderId: '778337091643',
    projectId: 'mindow-d931f',
    authDomain: 'mindow-d931f.firebaseapp.com',
    storageBucket: 'mindow-d931f.firebasestorage.app',
    measurementId: 'G-M79T0JG9QG',
  );
}
